### ISSUE TITLE
scheduler.yield seems to supersede image loading operations

### ISSUE THREAD

**Issue by Fleker** [WICG/scheduling-apis#77]
I have an app where the users can have a lot of items and there's a need to filter them. These filter operations, run on each item in their collection, can take a long time. For a while I've been using the `setTimeout` workaround to defer to the UI thread periodically in order to show some of the items as the larger filter process continues, which may be for several seconds.

I optionally added the `scheduler.yield` feature, which I hoped would improve performance. I haven't done a thorough test of speeds or page responsiveness, but I have noticed some strange behavior when results include unloaded images.

In this [demo video](https://youtu.be/Xl7e6fjKzic?t=28), starting at 28s, sprites for results that haven't loaded on the webpage yet are not going to load until the completion of the filter. Other UI affordances, like updating the progress bar and pagination, do continue to update.

Then I disable a flag in the app and revert back to the setTimeout behavior and do a page refresh. You can see in this second action that the sprites load as soon as they appear in the results.

Images that have previously been loaded on the page do seem to be loaded fine, such as the red **1** background. But it seems like there's some other blocking happening which I would consider detrimental to the user experience.

**Comment by shaseley** [comment]
Thanks, we're still trying to iron out which tasks yield continuations should be prioritized over, so this is really helpful feedback.

For images in particular, we recently made a change in Chrome to prioritize (main thread) image loading tasks (higher priority than yield() tasks), which should fix this particular issue (but there could be other similar issues). That change is enabled by default in Canary (M118) -- any chance you could try that and see if it's fixed?

**Comment by Fleker** [comment]
Thanks for reaching out. I had to put this to the side for a period as I had higher-priority tasks. When I run M120, Chrome Canary, I can see image loading only sometimes but when the long-running operation is many seconds long it doesn't quite get the behavior I got from `setTimeout(() => {}, 0)`

Here's an updated screencast: https://youtu.be/7Alf7sHyjlc

**Comment by verlok** [comment]
Hey, are there any updates on this topic, after several Chrome releases?

**Comment by Fleker** [comment]
On my side at least I still see some loading priority issues that make me reluctant to replace the current `setTimeout` approach.

**Comment by shaseley** [comment]
Sorry for the lag here. One of the goals of `yield()` is to prioritize continuations, so it will sometimes supersede other tasks. The idea is to let "higher priority" work run, with the main goal of letting apps break up long tasks while still letting input/rendering run --- to improve responsiveness issues --- so it's intentionally different than `setTimeout(,0)`. We're working on `scheduler.wait(milliseconds)` as a follow-up, which will be closer to `setTimeout` behavior --- but maybe with a different throttling mechanism, i.e. not clamping to 4ms after hitting the nesting limit.

So I don't think `yield()` will fit every scheduling use case, but we may also visit our (Chromium's) scheduling policy to revisit what the relative ordering of continuations (yield()) and other tasks should be.  But the tricky thing is that loading tasks have the same priority as `setTimeout()` and most other tasks ((in Chromium -- the spec gives flexibility).

I'll close this out for now, but please file a Chromium bug (crbug.com/new, component: Chromium>Blink>Scheduling>APIs) with a trace (ui.perfetto.dev or devtools) if you think there's an opportunity to improve on the `setTimeout()` approach. I'd be curious what task ordering changes would improve performance in this case.
